service: serverless-1
frameworkVersion: '3'		
useDotenv: true
provider:

  name: aws
  runtime: nodejs18.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
    EVENTBRIDGE_BUS_NAME: ${self:service}-${sls:stage}
    CONTENT_BUCKET_NAME: ${self:service}-${sls:stage}-website-bucket
    KIBO_HOME_HOST: ${env:KIBO_HOME_HOST}
    KIBO_CLIENT_ID: ${env:KIBO_CLIENT_ID}
    KIBO_CLIENT_SECRET: ${env:KIBO_CLIENT_SECRET}
  httpApi:
      cors: true
  iam:    
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "arn:aws:events:${aws:region}:*:event-bus/${self:provider.environment.EVENTBRIDGE_BUS_NAME}"
custom:
  client:
    bucketName: ${self:provider.environment.CONTENT_BUCKET_NAME}
    distributionFolder: config-ui/build
functions:
  getConfigs:
    handler: build/api/configs/list.handler
    events:
      - httpApi:
          path: /configs
          method: get  
  getConfigById:
    handler: build/api/configs/getById.handler
    events:
      - httpApi:
          path: /configs/{id}
          method: get
  updateConfig:
    handler: build/api/configs/upsert.handler
    events:
      - httpApi:
          path: /configs/{id}
          method: put
  catchAll:
    handler: build/api/catchAll.handler
    events:
      - httpApi: '*'
  dsWebhook:
    handler: build/producers/deliverySolutions.handler
    events:
      - http:
          path: /webhooks/ds
          method: post
  kiboWebhook:
    handler: build/producers/kibo.handler
    events:
      - http:
          path: /webhooks/kibo
          method: post
  dsEventHandler:
    handler: build/consumers/deliverySolutions.handler
    events:
      - eventBridge:
          eventBus: ${self:provider.environment.EVENTBRIDGE_BUS_NAME}
          pattern:
            source:
              - ds
  kiboEventHandler:
    handler: build/consumers/kibo.handler
    events:
      - eventBridge:
          eventBus:  ${self:provider.environment.EVENTBRIDGE_BUS_NAME}
          pattern:
            source:
              - kibo  
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
package:
  individually: true
  exclude:
    - config-ui/**
# plugins:
#   - serverless-esbuild
plugins:
  - serverless-lift
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-finch
  - serverless-webpack


  


